//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.TestBotSrv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TestBotSrv.ITestBotService")]
    public interface ITestBotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestBotService/GetUser", ReplyAction="http://tempuri.org/ITestBotService/GetUserResponse")]
        bool GetUser(int position, long tlgUserId, string tlgUserName, string lastEnter, int bestResult);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITestBotService/GetUser", ReplyAction="http://tempuri.org/ITestBotService/GetUserResponse")]
        System.Threading.Tasks.Task<bool> GetUserAsync(int position, long tlgUserId, string tlgUserName, string lastEnter, int bestResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITestBotServiceChannel : WindowsFormsApp1.TestBotSrv.ITestBotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestBotServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.TestBotSrv.ITestBotService>, WindowsFormsApp1.TestBotSrv.ITestBotService {
        
        public TestBotServiceClient() {
        }
        
        public TestBotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestBotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestBotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestBotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool GetUser(int position, long tlgUserId, string tlgUserName, string lastEnter, int bestResult) {
            return base.Channel.GetUser(position, tlgUserId, tlgUserName, lastEnter, bestResult);
        }
        
        public System.Threading.Tasks.Task<bool> GetUserAsync(int position, long tlgUserId, string tlgUserName, string lastEnter, int bestResult) {
            return base.Channel.GetUserAsync(position, tlgUserId, tlgUserName, lastEnter, bestResult);
        }
    }
}
